First line of code ;)

In [1]:
println("Hello World")

Hello World


In [2]:
"Hello World"

"Hello World"

Integer types

In [3]:
a = 100
b = 220
c = a+b

320

In [4]:
typeof(c)

Int64

In [5]:
d = 100.1
e = 220.6
f = d+e

320.7

In [6]:
typeof(f)

Float64

Strings

In [7]:
str1 = "hans"
str2 = "dieter"

"dieter"

In [8]:
str3 = str1*str2

"hansdieter"

In [9]:
typeof(str3)

String

Array introduction

In [10]:
x = zeros(1000)

1000-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

How arrays work
1 indexd

In [11]:
x[1]

0.0

In [12]:
length(x)

1000

Loop works a bit different with the  `end` keyword
we can use intendations but don't need to

In [13]:
for i in 1:length(x)
    x[i] = i*0.01
end

In [17]:
x

1000-element Vector{Float64}:
  0.01
  0.02
  0.03
  0.04
  0.05
  0.06
  0.07
  0.08
  0.09
  0.1
  0.11
  0.12
  0.13
  ⋮
  9.89
  9.9
  9.91
  9.92
  9.93
  9.94
  9.950000000000001
  9.96
  9.97
  9.98
  9.99
 10.0

In [18]:
x[1:4]

4-element Vector{Float64}:
 0.01
 0.02
 0.03
 0.04

Use sinus function on value

In [19]:
sin(x[1])

0.009999833334166664

Use sinus function on whole array

In [20]:
y = sin.(x)

1000-element Vector{Float64}:
  0.009999833334166664
  0.01999866669333308
  0.02999550020249566
  0.03998933418663416
  0.04997916927067833
  0.059964006479444595
  0.06994284733753277
  0.0799146939691727
  0.08987854919801104
  0.09983341664682815
  0.10977830083717481
  0.11971220728891936
  0.12963414261969486
  ⋮
 -0.44862125384280294
 -0.4575358937753214
 -0.4664047804997409
 -0.4752270271347798
 -0.48400175146312646
 -0.49272807601966023
 -0.5014051281791989
 -0.5100320402437544
 -0.5186079495293108
 -0.527131998452086
 -0.5356033346142913
 -0.5440211108893698

Plotting what we have done
using the package GLMakie 
show website

In [21]:
using GLMakie

No need for any other packages, as Julia is powerfull by itself no numpy 

Doing it the fast way, Lines function plots a line out of two arrays one x, one y coordinates

In [22]:
fig = lines(x,y)
display(fig)

GLMakie.Screen(...)

Doing it the right way ;)

In [23]:
fig2 = Figure(resolution = (1500,1500))
display(fig2)

GLMakie.Screen(...)

In [24]:
ax = Axis(fig2[1,1],title = "my first fig")
lines!(ax,x,y)

Lines{Tuple{Vector{Point{2, Float32}}}}

Small syntax convention in julia functions with a `!` modify the input argument, without `!` return a new object

Opens in seperate window in case you want it inline use CairoMakie. Show different plotting functions. 

In [25]:
scatter!(ax,x,cos.(x),color = "grey",markersize = 12)

Scatter{Tuple{Vector{Point{2, Float32}}}}

## Make Animation

Declare variable start_points which says how much points we initially want to draw 

In [26]:
start_points = 5
set_theme!(theme_black())


In [27]:
ani_fig = Figure(resolution = (1500,1500))
ani_ax = Axis(ani_fig[1,1],title = "My first animation :)")
scatter!(ani_ax,x[1:start_points],y[1:start_points],color = "blue")
#make it look cool
display(ani_fig)

GLMakie.Screen(...)

In [28]:
for t in start_points:length(x)
    scatter!(ani_ax,x[t-1:t],y[t-1:t],color = "blue")
    sleep(0.001)
end

In [29]:
@async for t in start_points:length(x)
    scatter!(ani_ax,x[t-1:t],cos.(x[t-1:t]),color = "red")
    sleep(0.001)
end

Task (runnable) @0x000000000d224010

In [30]:
@async for t in start_points:length(x)
    lines!(ani_ax,x[t-1:t],sin.(y[t-1:t]),color = "green",linewith = 55)
    sleep(0.001)
end

Task (runnable) @0x000000000d227e10

In [32]:
@async for t in start_points:length(x)
    lines!(ani_ax,x[t-1:t],exp.(x[t-1:t]),color = "pink",linewidth = 10)
    sleep(0.001)
end

Task (runnable) @0x000000000daf45e0

In [47]:
ani_fig = Figure(resolution = (1000,1000))
ani_ax = Axis(ani_fig[1,1],title = "My first animation :)")
scatter!(ani_ax,x[1:start_points],y[1:start_points])
#make it look cool
set_theme!(theme_black())
display(ani_fig)

GLMakie.Screen(...)

In [40]:
@async record(ani_fig, "beautiful.mp4",start_points:length(x); framerate = 60) do t
    scatter!(ani_ax,x[t-1:t],y[t-1:t],color = "blue")
    lines!(ani_ax,x[t-1:t],cos.(x[t-1:t]),color = "red")
end

Task (runnable) @0x000000000cda22f0

Make some optimizations

In [46]:
@async record(ani_fig, "beautiful_fast.mp4",start_points:4:length(x); framerate = 60) do t
    scatter!(ani_ax,x[t-4:t],y[t-4:t],color = "blue")
    lines!(ani_ax,x[t-4:t],cos.(x[t-4:t]),color = "red")
end

Task (runnable) @0x000000000c11dd20